
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yf-enterprise?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
server:
  port: 8082
logging:
  config: classpath:logback.xml
  level:
    org.mybatis: debug
    org.springframework.web: trace

