
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yf-enterprise
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  port: 8082
logging:
  config: classpath:logback.xml

